//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philips_Hardware__Inventory_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int empid { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string level { get; set; }
        public string Active { get; set; }
    }
}
